name: Build Nativa (GraalVM) & Upload (Actions + Release)

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (release tag)
        if: github.event_name == 'release'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Checkout (branch)
        if: github.event_name != 'release'
        uses: actions/checkout@v4

      - name: Set up JDK (GraalVM)
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '25'
          cache: 'maven'

      - name: Build native image (skip tests)
        run: |
          set -e
          chmod +x mvnw
          ./mvnw -Pnative -DskipTests -Darch=${{ matrix.arch }} native:compile

      - name: Package artifact (zip)
        id: pack
        shell: bash
        run: |
          set -euo pipefail
          BINPATH=$(find target -maxdepth 1 -type f -perm -111 -printf "%p %s\n" \
            | sort -k2 -nr | head -n1 | awk '{print $1}')

          if [ -z "${BINPATH:-}" ] || [ ! -f "$BINPATH" ]; then
            echo "Native binary tidak ditemukan di target/." >&2
            ls -lah target || true
            exit 1
          fi

          APPNAME=$(basename "$BINPATH")

          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            SUFFIX="${{ github.event.release.tag_name }}"
          else
            SUFFIX="${GITHUB_RUN_ID}"
          fi

          ZIPNAME="${APPNAME}-linux-${{ matrix.arch }}-${SUFFIX}.zip"

          echo "Jalankan: ./${APPNAME}" > target/HOW_TO_RUN.txt
          (cd target && zip -r "../${ZIPNAME}" "$APPNAME" HOW_TO_RUN.txt >/dev/null)

          sha256sum "${ZIPNAME}" | tee "${ZIPNAME}.sha256"

          echo "zip=${ZIPNAME}" >> "$GITHUB_OUTPUT"
          echo "checksum=${ZIPNAME}.sha256" >> "$GITHUB_OUTPUT"

      - name: Upload artifact (Actions tab)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.zip }}
          path: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          if-no-files-found: error
          retention-days: 14

      - name: Upload assets to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
